localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=local-admin
    - POSTGRES_PASSWORD=localpswd
    - POSTGRES_DB=local-db

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=test-admin
    - POSTGRES_PASSWORD=testpswd
    - POSTGRES_DB=test-db